org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.builtInKotlin=true
android.disallowKotlinSourceSets=false
android.sourceset.disallowProvider=false
android.dependency.excludeLibraryComponentsFromConstraints=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
